# Generated by Django 4.0.2 on 2022-02-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jason', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
